"""NVIDIA Jetson SKU products (RFC 0001 S3e, part 2).

Every Jetson SKU is generated by ``scripts/generate_jetson_skus.py`` from its
family template plus the source DB. These tests hold the generated catalog to
both: the generator's output is what's on disk, the template's arithmetic
reproduces its own flagship and NVIDIA's published FP32, and every SKU fact
equals its source-DB figure.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import generate_jetson_skus as gen  # noqa: E402

from embodied_schemas import ProductKind  # noqa: E402
from embodied_schemas.loaders import load_compute_products  # noqa: E402
from embodied_schemas.sources import load_source_db  # noqa: E402


@pytest.fixture(scope="module")
def products():
    return load_compute_products()


@pytest.fixture(scope="module")
def db():
    return load_source_db()


SKU_IDS = [s.catalog_id for s in gen.SKUS]


def test_catalog_matches_generator():
    assert gen.run(write=False) == 0


def test_all_nine_skus_are_modules(products):
    assert len(SKU_IDS) == 9
    for sku_id in SKU_IDS:
        p = products[sku_id]
        assert p.kind is ProductKind.MODULE and p.sku is not None, sku_id


@pytest.mark.parametrize("sku", gen.SKUS, ids=lambda s: s.catalog_id)
def test_sku_facts_equal_source_db(products, db, sku):
    p = products[sku.catalog_id]
    s = sku.subject
    gpu = p.dies[0].blocks[0]
    assert gpu.num_sms * gpu.cuda_cores_per_sm == db.find("cuda_cores", s)[0].value
    assert p.sku.enabled("cuda_core") == db.find("cuda_cores", s)[0].value
    assert p.sku.enabled("cpu_core") == db.find("cpu_cores", s)[0].value
    assert p.memory.memory_gb == db.find("memory_capacity", s)[0].value
    assert (
        p.swapc2.cost.unit_price_1k_usd.value
        == db.find("unit_price", s, variant="qty_1000", listing="current")[0].value
    )
    mass = db.find("mass", s)
    assert p.swapc2.weight.mass_g.value == mass[0].value
    if not sku.flagship:
        assert gpu.memory.memory_size_gb == db.find("memory_capacity", s)[0].value
        assert gpu.memory.memory_bus_bits == db.find("memory_bus_width", s)[0].value


@pytest.mark.parametrize("sku", [s for s in gen.SKUS if not s.flagship], ids=lambda s: s.catalog_id)
def test_sibling_has_only_the_sourced_top_profile(products, db, sku):
    """One profile: NVIDIA's max GPU clock at the module's maximum power."""
    p = products[sku.catalog_id]
    (profile,) = p.power.thermal_profiles
    clocks = {o.variant: o.value for o in db.find("frequency", sku.subject)}
    assert profile.clock_mhz == clocks.get("gpu_max_super", clocks["gpu_max"])
    assert profile.tdp_watts == db.find("power", sku.subject, variant="max")[0].value


@pytest.mark.parametrize("sku", [s for s in gen.SKUS if s.flagship], ids=lambda s: s.catalog_id)
def test_template_arithmetic_reproduces_flagship_peaks(products, sku):
    """The fabric arithmetic used for siblings gives the flagship's stored
    headline at its default-profile clock."""
    p = products[sku.catalog_id]
    gpu = p.dies[0].blocks[0].model_dump(mode="json")
    peaks = gen.fabric_peaks(gpu, gpu["num_sms"], p.power.default_profile.clock_mhz)
    assert peaks["int8_tops"] == pytest.approx(p.performance.int8_tops, abs=0.01)
    assert peaks["bf16_tflops"] == pytest.approx(p.performance.bf16_tflops, abs=0.01)
    assert peaks["fp32_tflops"] == pytest.approx(p.performance.fp32_tflops, abs=0.01)


@pytest.mark.parametrize(
    "catalog_id,subject",
    [
        ("nvidia_jetson_agx_thor_128gb", "nvidia_jetson_t5000"),
        ("nvidia_jetson_t4000", "nvidia_jetson_t4000"),
    ],
)
def test_arithmetic_matches_nvidia_fp32(products, db, catalog_id, subject):
    """At NVIDIA's MAXN GPU clock, the template arithmetic gives NVIDIA's
    published FP32 TFLOPS."""
    fp32 = db.find("fp32_throughput", subject, variant="maxn")[0]
    gpu = products[catalog_id].dies[0].blocks[0].model_dump(mode="json")
    peaks = gen.fabric_peaks(gpu, gpu["num_sms"], fp32.conditions["gpu_clock_mhz"])
    assert peaks["fp32_tflops"] == pytest.approx(fp32.value, abs=0.01)


def test_thor_floorsweep_omits_withdrawn_tensor_counts(products):
    for sku_id in ("nvidia_jetson_agx_thor_128gb", "nvidia_jetson_t4000"):
        assert products[sku_id].sku.enabled("tensor_core") is None


def test_orin_floorsweep_states_tensor_cores(products, db):
    p = products["nvidia_jetson_orin_nx_16gb"]
    assert (
        p.sku.enabled("tensor_core")
        == db.find("tensor_cores", "nvidia_jetson_orin_nx_16gb")[0].value
    )


def test_launch_price_and_date_are_sourced(products, db):
    thor = products["nvidia_jetson_agx_thor_128gb"]
    launch = db.find("unit_price", "nvidia_jetson_t5000", variant="qty_1000", listing="launch")[0]
    assert thor.market.launch_msrp_usd == launch.value
    assert thor.market.launch_date == db.documents[launch.source_id].published


def test_floorsweep_mismatch_fails_generation(db, monkeypatch):
    """A source figure inconsistent with the template's per-SM count stops
    the generator rather than writing a wrong SKU."""
    bad = gen.SKUS[1]  # AGX Orin 32GB: 1792 CUDA = 7 TPC x 2 x 128
    obs = db.find("cuda_cores", bad.subject)[0]
    monkeypatch.setattr(obs, "value", 1800.0)
    with pytest.raises(ValueError, match="not a multiple"):
        gen.build(bad, db)
