"""Embodied Schemas - Shared schemas and data for embodied AI codesign.

This package provides:
- Pydantic models for hardware, models, sensors, use cases, and benchmarks
- Factual data catalog with validated YAML specifications
- Registry API for querying the data catalog
"""

from embodied_schemas.hardware import (
    HardwareEntry,
    HardwareCapability,
    HardwareType,
    FormFactor,
    PhysicalSpec,
    EnvironmentalSpec,
    PowerSpec,
    PowerMode,
    InterfaceSpec,
    SlotAssignment,
    SystemConfiguration,
)
from embodied_schemas.models import (
    ModelEntry,
    ModelType,
    ModelVariant,
    AccuracyBenchmark,
    MemoryRequirements,
)
from embodied_schemas.sensors import (
    SensorEntry,
    SensorCategory,
    CameraSpec,
    DepthSpec,
    LidarSpec,
)
from embodied_schemas.usecases import (
    UseCaseEntry,
    Constraint,
    ConstraintCriticality,
    SuccessCriterion,
)
from embodied_schemas.benchmarks import (
    BenchmarkResult,
    LatencyMetrics,
    PowerMetrics,
    MemoryMetrics,
    ThermalMetrics,
    Verdict,
    Confidence,
)
from embodied_schemas.analysis import (
    Bottleneck,
    RooflineResult,
    EnergyResult,
    MemoryResult,
    ConcurrencyResult,
    SubgraphBreakdown,
    GraphAnalysisResult,
    ComparisonResult,
    BatchSweepResult,
)
from embodied_schemas.scheduling import (
    OperatorTiming,
    DataTransfer,
    DataMovementAnalysis,
    ExecutionTargetUtilization,
    RateFeasibility,
    SchedulingAnalysisResult,
    ArchitectureAnalysisResult,
    OperatorBenchmarkResult,
    ArchitectureBenchmarkResult,
)
from embodied_schemas.gpu import (
    GPUEntry,
    GPUVendor,
    DieSpec,
    ComputeResources,
    ClockSpeeds,
    MemorySpec,
    MemoryType,
    TheoreticalPerformance,
    PowerSpec as GPUPowerSpec,
    EfficiencyMetrics,
    BoardSpec,
    FeatureSupport,
    MarketInfo,
    TargetMarket,
    GPUArchitectureSummary,
    Foundry,
    PCIeGen,
    PowerConnector,
)
from embodied_schemas.cpu import (
    CPUEntry,
    CPUVendor,
    CPUArchitecture,
    SocketType,
    TargetMarket as CPUTargetMarket,
    ProcessNode,
    CoreConfig,
    ClockSpeeds as CPUClockSpeeds,
    CacheSpec,
    MemorySpec as CPUMemorySpec,
    InstructionExtensions,
    PowerSpec as CPUPowerSpec,
    PlatformSpec,
    IntegratedGraphics,
    MarketInfo as CPUMarketInfo,
    CPUArchitectureSummary,
)
from embodied_schemas.npu import (
    NPUEntry,
    NPUVendor,
    NPUType,
    NPUInterface,
    ComputeSpec as NPUComputeSpec,
    MemorySpec as NPUMemorySpec,
    PowerSpec as NPUPowerSpec,
    SoftwareSpec as NPUSoftwareSpec,
    PhysicalSpec as NPUPhysicalSpec,
    DataType as NPUDataType,
)
from embodied_schemas.operators import (
    OperatorEntry,
    OperatorCategory,
    IOSpec,
    ConfigParam,
    OperatorPerfProfile,
    ImplType,
)
from embodied_schemas.architectures import (
    SoftwareArchitecture,
    OperatorInstance,
    DataflowEdge,
    ArchitectureVariant,
    ExecutionTarget,
    EXECUTION_TARGET_INFO,
    architecture_to_mermaid,
)
from embodied_schemas.mission import (
    CapabilityTierEntry,
    CapabilityTierName,
    MissionProfileEntry,
    BatteryEntry,
    BatteryChemistry,
    SubsystemType,
    CoolingType,
    ThermalConstraints,
    FormFactorConstraints,
    PowerAllocation,
    DutyCycle,
    OperatingTemperatureRange,
)
from embodied_schemas.process_node import (
    ProcessNodeEntry,
    LibraryDensity,
    CircuitClass,
    TransistorTopology,
    DataConfidence,
)
from embodied_schemas.cooling_solution import (
    CoolingSolutionEntry,
    CoolingMechanism,
)
from embodied_schemas.kpu import (
    KPUEntry,
    KPUArchitecture,
    KPUArchitectureBase,
    KPUTileSpec,
    KPUTileScheduleClass,
    KPUNoCSpec,
    KPUMemorySubsystem,
    KPUSiliconBin,
    SiliconBinBlock,
    TransistorSource,
    TransistorSourceKind,
    KPUDieSpec,
    KPUClocks,
    KPUTheoreticalPerformance,
    KPUThermalProfile,
    KPUPowerSpec,
    KPUMarket,
    KPUTileKind,
    TileFootprint,
    LocalMemory,
    LocalMemoryLevel,
    LocalMemoryScope,
    TilePlacement,
    TilePlacementAffinity,
    tile_class_slug,
    KPUTileBase,
    PEFabricTile,
    SystolicTile,
    SystolicKernel,
    FixedFunctionTile,
    AnyKPUTile,
    CheckerboardSpec,
    CheckerboardPlacement,
    CheckerboardMemoryCell,
    SiteGrid,
    SPARE_SITE,
    PROGRAMMABLE_TILE_KINDS,
    derive_kpu_performance,
)
from embodied_schemas.kpu_tile_class import KPUTileClassEntry
from embodied_schemas.function_core import (
    WorkUnit,
    FunctionContract,
    FunctionThroughput,
    FunctionEnergy,
    FunctionIO,
    CoreSiliconBlock,
    FunctionCore,
)
from embodied_schemas.datapath import (
    NumberFormatFamily,
    NumberFormatSpec,
    NumberFormatName,
    parse_number_format,
    OpKind,
    DEFAULT_OPS_PER_INVOCATION,
    op_key,
    EnergyAnchor,
    RelativeEnergy,
    AbsoluteEnergy,
    EnergyRef,
    UnitMode,
    FunctionalUnit,
    PEDatapath,
)
from embodied_schemas.overlay import (
    NeighborTopology,
    FabricOverlayKind,
    OverlayScope,
    FabricOverlay,
    FabricInterconnect,
    NoCOverlayKind,
    NoCOverlay,
)
from embodied_schemas.compute_product import (
    ComputeProduct,
    ProductKind,
    PackagingKind,
    LifecycleStatus,
    DieRole,
    BlockKind,
    KPUBlock,
    AnyBlock,
    InterconnectLevel,
    TopologyKind,
    Interconnect,
    Die,
    Packaging,
    Power,
    Market,
)
from embodied_schemas.gpu_block import (
    GPUBlock,
    GPUComputeFabric,
    GPUMemorySubsystem,
    GPUOnDieFabric,
    GPUThermalProfile,
    GPUTheoreticalPerformance,
    GPUFabricKind,
    GPUL1Kind,
    GPUL2Topology,
    GPUNoCTopology,
    ClockDomain,
)
from embodied_schemas.cpu_block import (
    CPUBlock,
    CPUComputeFabric,
    CoreClusterSpec,
    CPUMemorySubsystem,
    CPUOnDieFabric,
    CPUThermalProfile,
    CPUTheoreticalPerformance,
    CoreClusterKind,
    CPUISAExtension,
    L2Layout,
    CPUNoCTopology,
)
from embodied_schemas.npu_block import (
    NPUBlock,
    NPUComputeFabric,
    NPUMemorySubsystem,
    NPUOnDieFabric,
    NPUThermalProfile,
    NPUTheoreticalPerformance,
    NPUDataflowKind,
    NPUNoCTopology,
    NPUSramLayout,
    KVCacheSpec,
    KVCacheStreamingKind,
)
from embodied_schemas.cgra_block import (
    CGRABlock,
    CGRAComputeFabric,
    CGRAMemorySubsystem,
    CGRAOnDieFabric,
    CGRAThermalProfile,
    CGRATheoreticalPerformance,
    CGRAFabricKind,
    CGRANoCTopology,
)
from embodied_schemas.dpu_block import (
    DPUBlock,
    DPUComputeFabric,
    DPUMemorySubsystem,
    DPUOnDieFabric,
    DPUThermalProfile,
    DPUTheoreticalPerformance,
    DPUFabricKind,
    DPUNoCTopology,
)
from embodied_schemas.tpu_block import (
    TPUBlock,
    TPUComputeFabric,
    TPUTileEnergyCoefficients,
    TPUMemorySubsystem,
    TPUOnDieFabric,
    TPUThermalProfile,
    TPUTheoreticalPerformance,
    TPUFabricKind,
    TPUNoCTopology,
)
from embodied_schemas.dsp_block import (
    DSPBlock,
    DSPComputeFabric,
    DSPMemorySubsystem,
    DSPThermalProfile,
    DSPTheoreticalPerformance,
    DSPFabricKind,
    DSPDeploymentKind,
)
from embodied_schemas.io_block import (
    IOBlock,
    IOMemorySubsystem,
    IOOnDieFabric,
    IOFabricTopology,
    InterSocketLink,
)
from embodied_schemas.compute_block_common import (
    DramAttachment,
    OnDieFabric,
    PCIeGen,
    TheoreticalPerformance,
    ThermalProfile,
    PowerDomain,
    PowerDomainKind,
    SiteRange,
    DomainOperatingPoint,
)
from embodied_schemas.registry import Registry
from embodied_schemas.loaders import (
    load_gpus,
    load_gpu_architectures,
    load_cpus,
    load_cpu_architectures,
    load_npus,
    load_hardware,
    load_chips,
    load_models,
    load_sensors,
    load_usecases,
    load_benchmarks,
    load_operators,
    load_architectures,
    load_capability_tiers,
    load_mission_profiles,
    load_batteries,
    load_process_nodes,
    load_cooling_solutions,
    load_kpus,
    load_kpu_tile_classes,
    load_compute_products,
)

# Kept equal to pyproject.toml's version by
# test_version_matches_pyproject. It is a literal rather than a read of
# the installed distribution metadata, because an editable install can
# carry stale metadata -- this very checkout reports 0.8.0 that way -- and
# a development consumer would then see the wrong number.
#
# It drifted before that test existed: 0.10.0 and 0.11.0 both shipped
# reporting "0.9.0", because a release bumps pyproject and nothing pointed
# back here.
__version__ = "0.13.0"

__all__ = [
    # Hardware
    "HardwareEntry",
    "HardwareCapability",
    "HardwareType",
    "FormFactor",
    "PhysicalSpec",
    "EnvironmentalSpec",
    "PowerSpec",
    "PowerMode",
    "InterfaceSpec",
    "SlotAssignment",
    "SystemConfiguration",
    # Models
    "ModelEntry",
    "ModelType",
    "ModelVariant",
    "AccuracyBenchmark",
    "MemoryRequirements",
    # Sensors
    "SensorEntry",
    "SensorCategory",
    "CameraSpec",
    "DepthSpec",
    "LidarSpec",
    # Use Cases
    "UseCaseEntry",
    "Constraint",
    "ConstraintCriticality",
    "SuccessCriterion",
    # Benchmarks
    "BenchmarkResult",
    "LatencyMetrics",
    "PowerMetrics",
    "MemoryMetrics",
    "ThermalMetrics",
    "Verdict",
    "Confidence",
    # Analysis (Graph Analysis)
    "Bottleneck",
    "RooflineResult",
    "EnergyResult",
    "MemoryResult",
    "ConcurrencyResult",
    "SubgraphBreakdown",
    "GraphAnalysisResult",
    "ComparisonResult",
    "BatchSweepResult",
    # Scheduling (Architecture Analysis)
    "OperatorTiming",
    "DataTransfer",
    "DataMovementAnalysis",
    "ExecutionTargetUtilization",
    "RateFeasibility",
    "SchedulingAnalysisResult",
    "ArchitectureAnalysisResult",
    # Benchmarking (Architecture)
    "OperatorBenchmarkResult",
    "ArchitectureBenchmarkResult",
    # GPU
    "GPUEntry",
    "GPUVendor",
    "DieSpec",
    "ComputeResources",
    "ClockSpeeds",
    "MemorySpec",
    "MemoryType",
    "TheoreticalPerformance",
    "GPUPowerSpec",
    "EfficiencyMetrics",
    "BoardSpec",
    "FeatureSupport",
    "MarketInfo",
    "TargetMarket",
    "GPUArchitectureSummary",
    "Foundry",
    "PCIeGen",
    "PowerConnector",
    # CPU
    "CPUEntry",
    "CPUVendor",
    "CPUArchitecture",
    "SocketType",
    "CPUTargetMarket",
    "ProcessNode",
    "CoreConfig",
    "CPUClockSpeeds",
    "CacheSpec",
    "CPUMemorySpec",
    "InstructionExtensions",
    "CPUPowerSpec",
    "PlatformSpec",
    "IntegratedGraphics",
    "CPUMarketInfo",
    "CPUArchitectureSummary",
    # NPU
    "NPUEntry",
    "NPUVendor",
    "NPUType",
    "NPUInterface",
    "NPUComputeSpec",
    "NPUMemorySpec",
    "NPUPowerSpec",
    "NPUSoftwareSpec",
    "NPUPhysicalSpec",
    "NPUDataType",
    # Registry
    "Registry",
    # Operators
    "OperatorEntry",
    "OperatorCategory",
    "IOSpec",
    "ConfigParam",
    "OperatorPerfProfile",
    "ImplType",
    # Architectures
    "SoftwareArchitecture",
    "OperatorInstance",
    "DataflowEdge",
    "ArchitectureVariant",
    "ExecutionTarget",
    "EXECUTION_TARGET_INFO",
    "architecture_to_mermaid",
    # Mission / Capability Tiers
    "CapabilityTierEntry",
    "CapabilityTierName",
    "MissionProfileEntry",
    "BatteryEntry",
    "BatteryChemistry",
    "SubsystemType",
    "CoolingType",
    "ThermalConstraints",
    "FormFactorConstraints",
    "PowerAllocation",
    "DutyCycle",
    "OperatingTemperatureRange",
    # Process Node (silicon fabrication catalog)
    "ProcessNodeEntry",
    "LibraryDensity",
    "CircuitClass",
    "TransistorTopology",
    "DataConfidence",
    # Cooling Solution (thermal removal catalog, peer of ProcessNode)
    "CoolingSolutionEntry",
    "CoolingMechanism",
    # Loaders
    "load_gpus",
    "load_gpu_architectures",
    "load_cpus",
    "load_cpu_architectures",
    "load_npus",
    "load_hardware",
    "load_chips",
    "load_models",
    "load_sensors",
    "load_usecases",
    "load_benchmarks",
    "load_operators",
    "load_architectures",
    "load_capability_tiers",
    "load_mission_profiles",
    "load_batteries",
    "load_process_nodes",
    "load_cooling_solutions",
    "load_kpus",
    "load_compute_products",
    # KPU SKU
    "KPUEntry",
    "KPUArchitecture",
    "KPUArchitectureBase",
    "KPUTileSpec",
    "KPUTileScheduleClass",
    "KPUNoCSpec",
    "KPUMemorySubsystem",
    "KPUSiliconBin",
    "SiliconBinBlock",
    "TransistorSource",
    "TransistorSourceKind",
    "KPUDieSpec",
    "KPUClocks",
    "KPUTheoreticalPerformance",
    "KPUThermalProfile",
    "KPUPowerSpec",
    "KPUMarket",
    "KPUTileKind",
    "TileFootprint",
    "LocalMemory",
    "LocalMemoryLevel",
    "LocalMemoryScope",
    "TilePlacement",
    "TilePlacementAffinity",
    "tile_class_slug",
    "KPUTileBase",
    "PEFabricTile",
    "SystolicTile",
    "SystolicKernel",
    "FixedFunctionTile",
    "AnyKPUTile",
    # Checkerboard (graphs#268 B4)
    "CheckerboardSpec",
    "CheckerboardPlacement",
    "CheckerboardMemoryCell",
    "SiteGrid",
    "SPARE_SITE",
    # Performance roll-up (graphs#268 B5)
    "PROGRAMMABLE_TILE_KINDS",
    "derive_kpu_performance",
    # Tile-class library (graphs#268 B6)
    "KPUTileClassEntry",
    "load_kpu_tile_classes",
    # Function cores (graphs#268 B3): fixed-function compute segments
    "WorkUnit",
    "FunctionContract",
    "FunctionThroughput",
    "FunctionEnergy",
    "FunctionIO",
    "CoreSiliconBlock",
    "FunctionCore",
    # Datapath (graphs#268 B1): number formats, operators, PE datapaths
    "NumberFormatFamily",
    "NumberFormatSpec",
    "NumberFormatName",
    "parse_number_format",
    "OpKind",
    "DEFAULT_OPS_PER_INVOCATION",
    "op_key",
    "EnergyAnchor",
    "RelativeEnergy",
    "AbsoluteEnergy",
    "EnergyRef",
    "UnitMode",
    "FunctionalUnit",
    "PEDatapath",
    # Overlays (graphs#268 B2): PE-level and NoC-level interconnect overlays
    "NeighborTopology",
    "FabricOverlayKind",
    "OverlayScope",
    "FabricOverlay",
    "FabricInterconnect",
    "NoCOverlayKind",
    "NoCOverlay",
    # ComputeProduct (v1 + v2) -- unified spine, additive
    "ComputeProduct",
    "ProductKind",
    "PackagingKind",
    "LifecycleStatus",
    "DieRole",
    "BlockKind",
    "KPUBlock",
    "AnyBlock",
    "InterconnectLevel",
    "TopologyKind",
    "Interconnect",
    "Die",
    "Packaging",
    "Power",
    "Market",
    # GPUBlock + supporting types (v2, additive)
    "GPUBlock",
    "GPUComputeFabric",
    "GPUMemorySubsystem",
    "GPUOnDieFabric",
    "GPUThermalProfile",
    "GPUTheoreticalPerformance",
    "GPUFabricKind",
    "GPUL1Kind",
    "GPUL2Topology",
    "GPUNoCTopology",
    "ClockDomain",
    # CPUBlock + supporting types (v3, additive)
    "CPUBlock",
    "CPUComputeFabric",
    "CoreClusterSpec",
    "CPUMemorySubsystem",
    "CPUOnDieFabric",
    "CPUThermalProfile",
    "CPUTheoreticalPerformance",
    "CoreClusterKind",
    "CPUISAExtension",
    "L2Layout",
    "CPUNoCTopology",
    # NPUBlock + supporting types (v4, additive)
    "NPUBlock",
    "NPUComputeFabric",
    "NPUMemorySubsystem",
    "NPUOnDieFabric",
    "NPUThermalProfile",
    "NPUTheoreticalPerformance",
    "NPUDataflowKind",
    "NPUNoCTopology",
    "NPUSramLayout",
    "KVCacheSpec",
    "KVCacheStreamingKind",
    "CGRABlock",
    "CGRAComputeFabric",
    "CGRAMemorySubsystem",
    "CGRAOnDieFabric",
    "CGRAThermalProfile",
    "CGRATheoreticalPerformance",
    "CGRAFabricKind",
    "CGRANoCTopology",
    "DPUBlock",
    "DPUComputeFabric",
    "DPUMemorySubsystem",
    "DPUOnDieFabric",
    "DPUThermalProfile",
    "DPUTheoreticalPerformance",
    "DPUFabricKind",
    "DPUNoCTopology",
    "TPUBlock",
    "TPUComputeFabric",
    "TPUTileEnergyCoefficients",
    "TPUMemorySubsystem",
    "TPUOnDieFabric",
    "TPUThermalProfile",
    "TPUTheoreticalPerformance",
    "TPUFabricKind",
    "TPUNoCTopology",
    "DSPBlock",
    "DSPComputeFabric",
    "DSPMemorySubsystem",
    "DSPThermalProfile",
    "DSPTheoreticalPerformance",
    "DSPFabricKind",
    "DSPDeploymentKind",
    # v13 IOBlock (first non-compute block kind)
    "IOBlock",
    "IOMemorySubsystem",
    "IOOnDieFabric",
    "IOFabricTopology",
    "InterSocketLink",
    # v8/v9/v10/v11/v13 unified primitives (compute_block_common)
    "TheoreticalPerformance",
    "ThermalProfile",
    "PCIeGen",
    "OnDieFabric",
    "DramAttachment",
    # Power domains (graphs#268 B4)
    "PowerDomain",
    "PowerDomainKind",
    "SiteRange",
    "DomainOperatingPoint",
    # Version
    "__version__",
]
